version: '2'
services:
  db:
    image: postgres
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}